# Generated by Django 5.1 on 2024-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_pnr', models.CharField(max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=10, unique=True)),
                ('complaint_time', models.DateTimeField()),
                ('complaint_summary', models.CharField(max_length=1000, unique=True)),
                ('complaint_status', models.CharField(max_length=10, unique=True)),
                ('complaint_brief', models.TextField()),
            ],
        ),
    ]
