# Generated by Django 5.1 on 2024-08-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_complaint_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_time',
        ),
    ]
