# Generated by Django 5.1 on 2024-08-17 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_complaint_complaint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='client_pnr',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
