# Generated by Django 5.1 on 2024-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_complaint_complaint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='client_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_summary',
            field=models.CharField(max_length=1000),
        ),
    ]
