# Generated by Django 5.1 on 2024-08-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
