# Generated by Django 5.1 on 2024-08-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123456, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('medical', 'Medical'), ('cleaning', 'Cleaning'), ('electric', 'Electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
